In [9]:
import json
from Bio import SeqIO
from Bio import pairwise2
from sklearn.cluster import AgglomerativeClustering
import numpy as np
import os
from tqdm import tqdm
import pickle
import shutil

In [10]:
deepfold_train_data_path = '/data/JSG/mapping_list/240226_deepfold_train_data_list.json'
#jsg_train_data_path = '/data/JSG/240226_JSG_protein_mapping.json'

fasta_root = '/data/JSG/fasta/'
fastas = os.listdir(fasta_root)

In [11]:
with open(deepfold_train_data_path, "r") as f:
    cluster_info = json.load(f)
    
#with open(jsg_train_data_path, "r") as f:
#    protein_targets = json.load(f)

In [12]:
feature_root = '/data/JSG/240429_feature_dir_with_binned_SA/'
feature_candidates = os.listdir(feature_root)

features = []
for candidate in feature_candidates:
    features.append(candidate.split('.')[0])
print('len(features)', len(features))

MSA_root = '/data1/JSG/alignment_dir/'
MSA_candidates = os.listdir(MSA_root)

MSAs = []

for candidate in MSA_candidates:
    MSAs.append(candidate.split('.')[0])
print('len(MSAs)',len(MSAs))

SAs = []
SA_root = '/data/JSG/SolventAcc_binned/'
SA_candidates = os.listdir(SA_root)

for candidate in SA_candidates:
    SAs.append(candidate.split('.')[0])
print('len(SAs)',len(SAs))

len(features) 16441
len(MSAs) 533503
len(SAs) 16441


In [13]:
len(cluster_info)

20032

In [14]:
feature_list = os.listdir('/data/jsg_bk/feature_dir/')

In [15]:
import os
import shutil
from concurrent.futures import ThreadPoolExecutor, as_completed
from tqdm.notebook import tqdm

In [16]:
former_root = '/data/jsg_bk/feature_dir/'
after_root  = '/data/JSG/240429_feature_dir_with_binned_SA/'

def copy_file(cluster):
    try:
        name = cluster.split('/')[-1].split('.')[0]
        code_name = name.split('_')[0]
        chain_name = name.split('_')[2]
        protein_name = (code_name + '_' + chain_name).lower()
        former_path = os.path.join(former_root, protein_name + '.pkl')
        after_path = os.path.join(after_root, protein_name + '.pkl')
        
        shutil.copy(former_path, after_path)
    except Exception as e:
        print(f"Failed to copy for cluster {cluster}: {e}")

# ThreadPoolExecutor를 사용하여 병렬로 파일 복사
#with ThreadPoolExecutor(max_workers=8) as executor:
#    futures = [executor.submit(copy_file, cluster) for cluster in cluster_info]

#    for future in tqdm(as_completed(futures), total=len(futures)):
#        pass

#print("모든 파일 복사가 완료되었습니다.")

In [17]:
#"""
protein_candidate = []

i = 0
for cluster in tqdm(cluster_info):
    name = cluster.split('/')[-1].split('.')[0]
    code_name = name.split('_')[0]
    chain_name = name.split('_')[2]
    protein_name = (code_name + '_' + chain_name).lower()

    if (protein_name in features) and (protein_name in SAs) and (protein_name not in protein_candidate):
        try : 
            feature_path = os.path.join(feature_root, protein_name) + '.pkl'
            with open(feature_path, 'rb') as f:
                data = pickle.load(f)

            #if data['aatype'].shape[0] > 0 :
            if data['solvent_acc_mask'].sum() > 0  and data['aatype'].shape[0] > 0 :
                protein_candidate.append(protein_name)
                i += 1
                
        except Exception as e:
            print(f"Error processing {cluster}: {str(e)}")
            
    if i == 2000:
        mapping = {}
        for i, candidate in enumerate(protein_candidate):
            mapping[i] = candidate
        with open('/data/JSG/mapping_list/240621_JSG_protein_mapping_new_2000.json', 'w') as json_file:
            json.dump(mapping, json_file, indent=4)
            
    if i == 5000:
        mapping = {}
        for i, candidate in enumerate(protein_candidate):
            mapping[i] = candidate
        with open('/data/JSG/mapping_list/240621_JSG_protein_mapping_new_5000.json', 'w') as json_file:
            json.dump(mapping, json_file, indent=4)    
                
    if i == 10000:
        mapping = {}
        for i, candidate in enumerate(protein_candidate):
            mapping[i] = candidate
        with open('/data/JSG/mapping_list/240621_JSG_protein_mapping_new_10000.json', 'w') as json_file:
            json.dump(mapping, json_file, indent=4)    
            
mapping = {}
for i, candidate in enumerate(protein_candidate):
    mapping[i] = candidate
with open('/data/JSG/mapping_list/240621_JSG_protein_mapping_new_full.json', 'w') as json_file:
    json.dump(mapping, json_file, indent=4)

  0%|          | 0/20032 [00:00<?, ?it/s]

Error processing ./train_data/outputs_384/c7/1c7t_1_A_350.xz: Ran out of input
Error processing ./train_data/outputs_384/c7/1c7t_1_A_0.xz: Ran out of input
Error processing ./train_data/outputs_384/c7/1c7t_1_A_473.xz: Ran out of input
Error processing ./train_data/outputs_384/c2/2c2n_1_A_0.xz: pickle data was truncated
Error processing ./train_data/outputs_384/k0/4k08_1_A_0.xz: pickle data was truncated
Error processing ./train_data/outputs_384/h0/1h0h_1_A_592.xz: Ran out of input
Error processing ./train_data/outputs_384/h0/4h0p_1_A_0.xz: pickle data was truncated
Error processing ./train_data/outputs_384/h0/1h0h_1_A_0.xz: Ran out of input
Error processing ./train_data/outputs_384/h0/1h0h_1_A_350.xz: Ran out of input
Error processing ./train_data/outputs_384/h0/4h0p_1_A_53.xz: pickle data was truncated
Error processing ./train_data/outputs_384/dz/3dzz_1_A_6.xz: pickle data was truncated
Error processing ./train_data/outputs_384/dz/3dzz_1_A_0.xz: pickle data was truncated
Error process

Error processing ./train_data/outputs_384/cy/2cy4_1_A_0.xz: pickle data was truncated
Error processing ./train_data/outputs_384/su/1sur_1_A_0.xz: pickle data was truncated
Error processing ./train_data/outputs_384/hr/6hr7_1_A_0.xz: pickle data was truncated
Error processing ./train_data/outputs_384/hr/6hr7_1_A_42.xz: pickle data was truncated
Error processing ./train_data/outputs_384/g2/6g26_1_E_0.xz: pickle data was truncated
Error processing ./train_data/outputs_384/px/3pxv_1_A_0.xz: pickle data was truncated
Error processing ./train_data/outputs_384/uq/5uqp_1_A_0.xz: pickle data was truncated
Error processing ./train_data/outputs_384/ec/6ecd_1_A_0.xz: pickle data was truncated
Error processing ./train_data/outputs_384/ec/5ecc_1_A_0.xz: pickle data was truncated
Error processing ./train_data/outputs_384/mv/3mvu_1_A_0.xz: pickle data was truncated
Error processing ./train_data/outputs_384/ef/2ef8_1_A_0.xz: pickle data was truncated
Error processing ./train_data/outputs_384/jd/5jd0_1_A

Error processing ./train_data/outputs_384/bh/3bhn_1_A_0.xz: pickle data was truncated
Error processing ./train_data/outputs_384/zb/2zb2_1_A_0.xz: pickle data was truncated
Error processing ./train_data/outputs_384/zb/2zb2_1_A_350.xz: pickle data was truncated
Error processing ./train_data/outputs_384/zb/2zb2_1_A_464.xz: pickle data was truncated
Error processing ./train_data/outputs_384/d5/2d5l_1_A_321.xz: pickle data was truncated
Error processing ./train_data/outputs_384/d5/4d5g_1_A_0.xz: pickle data was truncated
Error processing ./train_data/outputs_384/d5/4d5g_1_A_204.xz: pickle data was truncated
Error processing ./train_data/outputs_384/d5/2d5l_1_A_0.xz: pickle data was truncated
Error processing ./train_data/outputs_384/zo/4zos_1_A_0.xz: pickle data was truncated
Error processing ./train_data/outputs_384/a5/6a5f_1_A_0.xz: pickle data was truncated
Error processing ./train_data/outputs_384/bp/5bp2_1_A_0.xz: pickle data was truncated
Error processing ./train_data/outputs_384/jn/4

In [18]:
len(mapping)

16260

In [35]:
feature_path

'/data/JSG/240429_feature_dir_with_binned_SA/3lcz_a.pkl'

In [19]:
len(protein_candidate)

16260

In [20]:
print(len(features))

16441


In [29]:
with open(feature_path, 'rb') as f:
    data = pickle.load(f)
data.keys()

dict_keys(['aatype', 'between_segment_residues', 'domain_name', 'residue_index', 'seq_length', 'sequence', 'all_atom_positions', 'all_atom_mask', 'resolution', 'release_date', 'is_distillation', 'template_aatype', 'template_all_atom_positions', 'template_sum_probs', 'template_all_atom_mask', 'deletion_matrix_int', 'msa', 'num_alignments', 'solvent_acc', 'solvent_acc_binned', 'solvent_acc_real', 'solvent_acc_mask'])

In [22]:
data['solvent_acc_binned'].shape, data['solvent_acc_real'].shape, data['solvent_acc_mask'].shape

((53, 10), (53,), (53,))

In [32]:
data['solvent_acc_binned'].argmax(axis=-1)

array([9, 9, 4, 2, 5, 8, 5, 2, 3, 4, 5, 0, 6, 5, 1, 7, 5, 6, 0, 4, 5, 7,
       7, 6, 4, 0, 4, 6, 0, 7, 4, 7, 0, 2, 3, 4, 1, 6, 4, 0, 2, 5, 3, 4,
       6, 5, 5, 6, 8, 2, 5, 9, 9])

In [34]:
data['solvent_acc_binned'].sum(axis=-1)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1.,
       1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1., 1., 1., 0., 1.,
       1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1.])

In [24]:
data['solvent_acc_real']

array([192.01288635, 142.50012949,  72.45769296,  30.1907054 ,
        83.32634691, 131.63147555,  76.08057761,  45.88987221,
        71.25006475,  62.79666723,  78.49583404,   0.        ,
        97.8178855 ,  95.40262907,  18.11442324, 125.59333447,
        39.85173113,  73.66532118,   0.        , 100.23314193,
        96.61025728, 136.46198841, 103.85602658, 115.93230874,
        61.58903902,   1.20762822,  70.04243653, 121.97044982,
         7.2457693 , 130.42384733,  32.60596183, 147.33064236,
         2.41525643,  32.60596183,  53.13564151,  82.11871869,
        25.36019254,  78.49583404,  80.91109047,   7.2457693 ,
        31.39833362,  82.11871869,  62.79666723,  83.32634691,
       120.7628216 , 123.17807804,  91.77974442, 137.66961663,
       163.02980917,  56.75852615, 100.23314193, 181.14423241,
       192.01288635])

In [33]:
data['solvent_acc_binned']

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 